# Generated by Django 6.0.4 on 2026-06-12 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_whishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='whishlist',
            constraint=models.UniqueConstraint(fields=('user', 'products'), name='unique_user_product'),
        ),
    ]
